let A = document.getElementById("date");
let B = document.getElementById("current");
let C = document.getElementById("raw");
let D = document.getElementById("years");
let E = document.getElementById("years-decimal");
let F = document.getElementById("years-months");
let G = document.getElementById("years-months-decimal");
let H = document.getElementById("years-months-days");
let I = document.getElementById("years-days");
let J = document.getElementById("months");
let K = document.getElementById("months-decimal");
let L = document.getElementById("months-days");
let M = document.getElementById("days");
let N = document.getElementById("days-decimal");
let O = document.getElementById("days-hours");
let P = document.getElementById("days-hours-minutes");
let Q = document.getElementById("days-hours-minutes-seconds");
let R = document.getElementById("hours");
let S = document.getElementById("hours-decimal");
let T = document.getElementById("hours-minutes");
let U = document.getElementById("hours-minutes-decimals");
let V = document.getElementById("hours-minutes-seconds");
let W = document.getElementById("minutes");
let X = document.getElementById("minutes-decimal");
let Y = document.getElementById("minutes-seconds");
let Z = document.getElementById("seconds");
let a = new Date();
let b = new Date(Date.parse("16 Aug 2031 15:00:00 EST"));
let c = new Date(b.getTime() - a.getTime());
let d = (a / 1000 / 60 / 60 / 24 / 30.4167 / 12); // years
let e = (a / 1000 / 60 / 60 / 24 / 30.4167); // months
let f = (a / 1000 / 60 / 60 / 24); // days
let g = (a / 1000 / 60 / 60); // hours
let h = (a / 1000 / 60); // minutes;
let i = (a / 1000); // seconds;
let j = ((e) - (12 * Math.floor(d)))
let k = ((f) - (30.4167 * Math.floor(Z / 1000 / 60 / 60 / 24 / 30.4167)))
// let l = (())

if(Math.floor(e) == 0){
    e += 11;
}

A.innerText += " " + new Date("16 Aug 2031 15:00:00 EST").toString();
B.innerText += " " + b.toString();
C.innerText += " " + c.getTime();
D.innerText += " " + Math.round(d);
E.innerText += " " + d;
F.innerText += " " + Math.floor(d) + " years, " + Math.floor(j) + " months";
G.innerText += " " + Math.floor(d) + " years, " + j + " months";
H.innerText += " " + Math.floor(d) + " years, " + Math.floor(j) + " months, " + Math.floor(k) + " days"
I.innerText += " " + Math.floor(d) + " years, " + Math.floor(k) + " days";
J.innerText += " " + Math.round(e);
K.innerText += " " + e;
L.innerText += " " + Math.floor(e) + " months, " + Math.floor(k) + " days"
M.innerText += " " + Math.round(f);
N.innerText += " " + f;
O.innerText += " " + Math.round(g);
P.innerText += " " + g;
// Q,innerText += " " + 